# Generated by Django 6.0.2 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(),
        ),
    ]
